#!/usr/bin/env bash
# Installs nginx server
sudo apt-get update
sudo apt-get install nginx
sudo ufw 'Nginx HTTP'

echo "Hello World!" | sudo tee /var/www/html/index.html

#tesing nginx

sudo nginx -t

sudo service nginx reload
