#!/usr/bin/env bash
# The code creates the file /var/run/myscript.pid containing its PID
# It displays To infinity and beyond indefinitely
# It displays I hate the kill command when receiving a SIGTERM signal
# It displays Y U no love me?! when receiving a SIGINT signal
# It deletes the file /var/run/myscript.pid and terminates itself
echo "$$" > /var/run/myscript.pid

termfunc() {
	rm /var/run/myscript.pid
	exit
}


while true
do
	echo "To infinity and beyond"
	sleep 2
	trap 'echo "Y U no love me?!"' SIGINT
	trap 'echo "I hate the kill command" && termfunc' SIGTERM
	trap 'termfunc' SIGQUIT
done
