#!/usr/bin/env bash
# Firstly the code kills the infinity and beyond  program and get the pid of the program
id=$(pgrep "bash ./4-to_infinity_and_beyond" -f)

# Then terminate the infinate process
if [ -n "$id" ]
then
  kill -15 "$id"
fi
